import type { StyleDefinition } from "../shared/types.js";

export const AOYOSUMU_STYLE = {
  id: "style-aoyosumu",
  name: "Aoyosumu",
  description:
    "Aoyosumu is a style of martial arts centered on serenity, patience, and exploiting openings created by an opponent's aggression.",
  masteryMoveIds: [
    "move-aoyosumu-calming-mastery",
    "move-aoyosumu-ceasefire-mastery",
    "move-aoyosumu-counterstrike-mastery",
    "move-aoyosumu-leverage-mastery",
    "move-aoyosumu-technique-mastery",
    "move-aoyosumu-untouchable-mastery",
  ],
  skillMoveIds: [
    "move-aoyosumu-close-shave",
    "move-aoyosumu-inner-peace",
    "move-aoyosumu-state-of-zen",
    "move-aoyosumu-stoicism",
    "move-aoyosumu-the-untroubled-mind",
    "move-aoyosumu-calming-the-battlefield",
    "move-aoyosumu-opportunist",
    "move-aoyosumu-quiet-preparation",
    "move-aoyosumu-reversal-of-fortune",
  ],
  advancedAttackMoveIds: [
    "move-aoyosumu-bullwhip",
    "move-aoyosumu-crescent-kick",
    "move-aoyosumu-floating-drop",
    "move-aoyosumu-heart-punch",
    "move-aoyosumu-lights-out-strike",
    "move-aoyosumu-one-arm-shoulder-throw",
    "move-aoyosumu-return-fire",
    "move-aoyosumu-serenity-wave",
    "move-aoyosumu-straightjacket",
    "move-aoyosumu-swift-neck-chop",
    "move-aoyosumu-weeping-willow",
    "move-aoyosumu-wind-shove",
    "move-aoyosumu-zen-explosion",
    "move-aoyosumu-bomb-tag",
    "move-aoyosumu-braced-energy-beam",
    "move-aoyosumu-breakout",
    "move-aoyosumu-breathtaker",
    "move-aoyosumu-dashing-fist-drive",
    "move-aoyosumu-crushing-kick",
    "move-aoyosumu-hundred-point-strike",
    "move-aoyosumu-karmic-possession",
    "move-aoyosumu-push",
    "move-aoyosumu-shaolin-cross-punch",
    "move-aoyosumu-silence-gun",
    "move-aoyosumu-tiger-strikes",
    "move-aoyosumu-tranquil-strike",
    "move-aoyosumu-trapped-strikes",
    "move-aoyosumu-elevated-kick",
    "move-aoyosumu-frost-wind-technique",
    "move-aoyosumu-nowhere-wave",
    "move-aoyosumu-sky-dance-technique",
    "move-aoyosumu-slow-charge",
    "move-aoyosumu-super-arm-bar-takedown",
    "move-aoyosumu-tears-of-the-mystic",
  ],
  signatureMoveIds: [
    "move-aoyosumu-creeping-death",
    "move-aoyosumu-epitaph-to-war",
    "move-aoyosumu-heavenly-execution",
    "move-aoyosumu-serenity-explosion",
    "move-aoyosumu-sonic-whisper",
    "move-aoyosumu-the-secret-of-the-universe",
  ],
  blockMoveIds: [
    "move-aoyosumu-blast-shield",
    "move-aoyosumu-defiant-stance",
    "move-aoyosumu-impenetrable-defense",
    "move-aoyosumu-screening",
    "move-aoyosumu-somersault-roll",
    "move-aoyosumu-stepping-on-toes",
  ],
  source: {
    path: "reference/moves/aoyosumu.md",
    text: "# Aoyosumu",
  },
} as const satisfies StyleDefinition;
