import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  AUTOMATED_NPC_POLICY_ASSIGNMENTS,
  npcReadinessMatrix,
  validateNpcPolicyCatalog,
} from "../packages/npc-ai/src/index.js";

const rows = npcReadinessMatrix((npcId) => AUTOMATED_NPC_POLICY_ASSIGNMENTS[npcId]);
const failures = rows.flatMap((row) => {
  const duplicate = rows.filter((candidate) => candidate.npcId === row.npcId).length !== 1;
  return duplicate ? [`NPC readiness row is not unique: ${row.npcId}`] : [];
});
const catalog = validateNpcPolicyCatalog();
const markdown = [
  "<!-- Generated by scripts/npc-ai-readiness.ts. Do not edit manually. -->",
  "# NPC-AI readiness matrix",
  "",
  `Generated rows: ${rows.length}. Automated: ${rows.filter((row) => row.runtimeClassification === "automated").length}. Manual-only: ${rows.filter((row) => row.runtimeClassification === "manual-only").length}.`,
  "",
  "| NPC ID | Source | HP | Power | Dexterity | Dex bonus | Race | Style | Moves | Unresolved moves | Items | Transformations | Battle notes | Runtime | Policy | Blockers |",
  "| --- | --- | --- | --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
  ...rows.map(
    (row) =>
      `| ${row.npcId} | ${row.sourceReference.path} | ${row.hpStatus} | ${row.powerStatus} | ${row.dexterityStatus} | ${row.dexterityBonusStatus} | ${row.raceReference ?? "—"} | ${row.styleReference ?? "—"} | ${row.resolvedMoves.length} | ${row.unresolvedMoves.join(", ") || "—"} | ${row.resolvedItems.join(", ") || "—"} | ${row.resolvedTransformations.join(", ") || "—"} | ${row.battleNotesStatus} | ${row.runtimeClassification} | ${row.effectivePolicyId ?? "—"} | ${row.issues.map((issue) => issue.reason).join(", ") || "—"} |`,
  ),
  "",
  "Policy catalog: " +
    (catalog.ok ? "valid" : catalog.issues.map((issue) => issue.message).join("; ")),
  "",
].join("\n");

if (process.argv.includes("--validate")) {
  if (rows.length !== new Set(rows.map((row) => row.npcId)).size)
    failures.push("NPC readiness matrix contains duplicate IDs.");
  if (rows.length === 0) failures.push("NPC readiness matrix is empty.");
  if (!catalog.ok)
    failures.push(...catalog.issues.map((issue) => `${issue.path}: ${issue.message}`));
  if (failures.length > 0) throw new Error(failures.join("\n"));
  console.log(`Validated ${rows.length} NPC readiness rows.`);
} else {
  const outputPath = resolve("docs/architecture/npc-ai-readiness.md");
  await mkdir(resolve("docs/architecture"), { recursive: true });
  await writeFile(outputPath, markdown, "utf8");
  console.log(`Wrote ${outputPath}`);
}
